### ISSUE TITLE
正規表現んんんん

### ISSUE THREAD

**Issue by mochimilk** [mochimilk/retia-project#5]
re.serach(r"(?|....)",TEXT) でマッチングさせると「sre_constants.error: unknown extension ?| at position 1」エラーで停止。

**Comment by called-d** [comment]
https://docs.python.jp/3/library/re.html
`(?|...)` は無いですね。 `(?:...)` かと。見づらいですが `:` です

**Comment by mochimilk** [comment]
(?:...)でかわいいマッチのgroup(n)を取得できるようになった気がする。意味ないけど。

**Comment by mochimilk** [comment]
- *.?とかで貪欲にしない
- アサーションを使う
- むしろ許可した文字以外に反応させない

**Comment by mochimilk** [comment]
アサーションとか(?:...)とかの拡張使うと（）内の文字列が消費されない。
通常はマッチした部分がgroup(n)に順番に格納されるが、拡張パターン部分はマッチしてもgroup(n)に入らない。

**Comment by called-d** [comment]
正規表現のまとまりを作るためだけに()を使う、つまりgroup(n)に入れないための記法っぽいですからね

**Comment by mochimilk** [comment]
マッチした部分を抽出して使うようなときに(?:....)とかアサーションで書く。

[https://regex101.com/](https://regex101.com/)
ここで色々試せる
