### ISSUE TITLE
ストリーミングでタイムラインをどう拾うか

### ISSUE THREAD

**Issue by mochimilk** [mochimilk/retia-project#7]
def on_update(self, status):
        tl = mastodon.timeline(timeline='local', limit=1, max_id=None)

もしかして：on_updateが実行されればmastodon.timelineしなくてもstatusにタイムラインの中身入ってる？

**Comment by mochimilk** [comment]
合ってるか分からないけどtl = [status]で動いてはいる

**Comment by mochimilk** [comment]
他のタイムラインを拾いたかったらStreamListenerのクラスを増やす。
とりあえず動いてるからクローズ

**Comment by called-d** [comment]
どこかで tl = [] で作っておいて、tl.append(status) でリストに追加するとよい

**Comment by mochimilk** [comment]
重複チェックキャッシュ成功
